portal:
  base_url: "https://student.gcuf.edu.pk"
  login: "/login-process.php"
  verify_otp: "/login-process.php"
  profile: "/index.php"
  academics: "/academics.php"
  academics_details: "/ajax/academics-details-2020.php"